package com.reign.plugin.yx.common;

public enum TaobaoES
{
    TAOBAO_ERROR_COOPID_IS_EMPTY("TAOBAO_ERROR_COOPID_IS_EMPTY", 0, "0101", "COOPID_IS_EMPTY", 17), 
    TAOBAO_ERROR_TBORDERN0_IS_EMPTY("TAOBAO_ERROR_TBORDERN0_IS_EMPTY", 1, "0101", "TBORDERN0_IS_EMPTY", 2), 
    TAOBAO_ERROR_CARDID_IS_NOT_EMPTY("TAOBAO_ERROR_CARDID_IS_NOT_EMPTY", 2, "0101", "CARDID_IS_EMPTY", 3), 
    TAOBAO_ERROR_CARDNUMBER_IS_EMPTY("TAOBAO_ERROR_CARDNUMBER_IS_EMPTY", 3, "0101", "CARDNUMBER_IS_EMPTY", 4), 
    TAOBAO_ERROR_CUSTOMER_IS_EMPTY("TAOBAO_ERROR_CUSTOMER_IS_EMPTY", 4, "0101", "CUSTOMER_IS_EMPTY", 5), 
    TAOBAO_ERROR_SUM_IS_EMPTY("TAOBAO_ERROR_SUM_IS_EMPTY", 5, "0101", "SUM_IS_EMPTY", 6), 
    TAOBAO_ERROR_GAMEID_IS_EMPTY("TAOBAO_ERROR_GAMEID_IS_EMPTY", 6, "0101", "GAMEID_IS_EMPTY", 7), 
    TAOBAO_ERROR_SECTION1_IS_EMPTY("TAOBAO_ERROR_SECTION1_IS_EMPTY", 7, "0101", "SECTION1_IS_EMPTY", 8), 
    TAOBAO_ERROR_SECTION2_IS_EMPTY("TAOBAO_ERROR_SECTION2_IS_EMPTY", 8, "0101", "SECTION2_IS_EMPTY", 9), 
    TAOBAO_ERROR_TAOBAOORDERSNAP_IS_EMPTY("TAOBAO_ERROR_TAOBAOORDERSNAP_IS_EMPTY", 9, "0101", "TAOBAOORDERSNAP_IS_EMPTY", 10), 
    TAOBAO_ERROR_NOTIFYURL_IS_EMPTY("TAOBAO_ERROR_NOTIFYURL_IS_EMPTY", 10, "0101", "NOTIFYURL_IS_EMPTY", 11), 
    TAOBAO_ERROR_SIGN_IS_EMPTY("TAOBAO_ERROR_SIGN_IS_EMPTY", 11, "0101", "SIGN_IS_EMPTY", 12), 
    TAOBAO_ERROR_VERSION_IS_EMPTY("TAOBAO_ERROR_VERSION_IS_EMPTY", 12, "0101", "VERSION_IS_EMPTY", 13), 
    TAOBAO_ERROR_TIME_OUT("TAOBAO_ERROR_TIME_OUT", 13, "0101", "TIME_OUT", 14), 
    TAOBAO_ERROR_WRONG_TICKET("TAOBAO_ERROR_WRONG_TICKET", 14, "0102", "WRONG_TICKET", 15), 
    TAOBAO_ERROR_IP_IS_FORBIDDEN("TAOBAO_ERROR_IP_IS_FORBIDDEN", 15, "0101", "IP_IS_FORBIDDEN", 16), 
    TAOBAO_SUCCESS("TAOBAO_SUCCESS", 16, "", "SUCCESS", 1), 
    TAOBAO_ERROR_TBUSERID_IS_EMPTY("TAOBAO_ERROR_TBUSERID_IS_EMPTY", 17, "0101", "TBUSERID_IS_EMPTY", 18), 
    TAOBAO_ERROR_GATEWAYID_IS_EMPTY("TAOBAO_ERROR_GATEWAYID_IS_EMPTY", 18, "0101", "GATEWAYID_IS_EMPTY", 19), 
    TAOBAO_ERROR_ISADULT_IS_EMPTY("TAOBAO_ERROR_ISADULT_IS_EMPTY", 19, "0101", "ISADULT_IS_EMPTY", 20), 
    TAOBAO_ERROR_LOGINTIME_IS_EMPTY("TAOBAO_ERROR_LOGINTIME_IS_EMPTY", 20, "0101", "LOGINTIME_IS_EMPTY", 21), 
    TAOBAO_ERROR_ORDER_DOESNT_EXIST("TAOBAO_ERROR_ORDER_DOESNT_EXIST", 21, "0104", "ORDER_DOESNT_EXIST", 22), 
    TAOBAO_ERROR_EXCEPTION("TAOBAO_ERROR_EXCEPTION", 22, "0101", "EXCEPTION", 23), 
    TAOBAO_ERROR_ORDER_EXIST("TAOBAO_ERROR_ORDER_EXIST", 23, "0301", "DUPLICATE ORDER", 24), 
    TAOBAO_ERROR_PAY_FAIL("TAOBAO_ERROR_PAY_FAIL", 24, "0306", "PAY FAIL", 25), 
    TAOBAO_ERROR_COOPID_WRONG_REQUEST("TAOBAO_ERROR_COOPID_WRONG_REQUEST", 25, "0102", "COOPID_IS_WRONG", 26), 
    TAOBAO_ERROR_COOPID_WRONG_ORDER("TAOBAO_ERROR_COOPID_WRONG_ORDER", 26, "0306", "COOPID_IS_WRONG", 27), 
    TAOBAO_ERROR_CARDID_WRONG("TAOBAO_ERROR_CARDID_WRONG", 27, "0305", "CARDID_IS_WRONG", 28), 
    TAOBAO_ERROR_TYPE_IS_WRONG("TAOBAO_ERROR_TYPE_IS_WRONG", 28, "0101", "TYPE_IS_WRONG", 29);
    
    private int errorCodeLog;
    public String errorCode;
    public String errorString;
    
    public String getErrorCode() {
        return this.errorCode;
    }
    
    public void setErrorCode(final String errorCode) {
        this.errorCode = errorCode;
    }
    
    public String getErrorString() {
        return this.errorString;
    }
    
    public void setErrorString(final String errorString) {
        this.errorString = errorString;
    }
    
    public int getErrorCodeLog() {
        return this.errorCodeLog;
    }
    
    public void setErrorCodeLog(final int errorCodeLog) {
        this.errorCodeLog = errorCodeLog;
    }
    
    private TaobaoES(final String s, final int n, final String error, final String str, final int errorCodeLog) {
        this.errorCode = error;
        this.errorString = str;
        this.errorCodeLog = errorCodeLog;
    }
}
