package com.reign.plugin.yx.common;

public class YxOperationErrors
{
    public static final int SUCCESS = 1;
    public static final int ERROR_NO_ROLE = 2;
    public static final int ERROR_WRONG_ROLE = 3;
    public static final int ERROR_WRONG_GOLD = 4;
    public static final int ERROR_EXISTS_ORDERID = 5;
    public static final int ERROR_EXCEPTION = 6;
    public static final String ERROR_EXCEPTION_MESSAGE = "\u670d\u52a1\u5668\u5f02\u5e38";
    public static final int ERROR_ERROR_SIGN = 7;
    public static final int ERROR_NOT_PAY = 8;
    public static final int ERROR_NOTIRY_ERROR = 9;
    public static final int YX_IS_EMPTY = 901;
    public static final int USER_ID_IS_EMPTY = 902;
    public static final int PLAYER_ID_IS_EMPTY = 903;
    public static final int GOLD_IS_ERROR = 904;
    public static final int NO_OPERATION_CLASS_FOUND = 905;
    public static final int NOT_IMPLEMENT = 906;
    public static final int ORDER_ID_IS_EMPTY = 907;
    public static final int IP_IS_FORBIDDEN = 908;
    public static final int WRONG_TICKET = 909;
    public static final int TIMESTAMP_IS_EMPTY = 910;
    public static final int NOT_PRELOGIN = 911;
    public static final int LOGIN_NOT_FIT_PRELOGIN = 912;
    public static final int PAY_SERVICE_IS_NULL = 913;
    public static final int PLAYER_SERVICE_IS_NULL = 914;
    public static final int ADDITIONAL_KEY_IS_EMPTY = 915;
    public static final int PLAYER_NOT_EXSIT = 916;
    public static final int ORDER_ID_IS_EXSITED = 917;
    public static final int PAY_FAIL = 918;
    public static final int OTHER_ERROR = 919;
    public static final int MANAGER_SERVICE_IS_NULL = 920;
    public static final int RMB_IS_EMPTY = 921;
    public static final int TICKET_IS_EMPTY = 922;
    public static final int DATE_IS_EMPTY = 923;
    public static final int SERVER_ID_IS_EMPTY = 924;
    public static final int PAY_FINAL_FAIL = 1000;
    public static final int GAME_IS_EMPTY = 1001;
    public static final int BACKURL_IS_EMPTY = 1002;
    public static final int DWSERVID_IS_EMPTY = 1003;
    public static final int TOCKEN_IS_EMPTY = 1004;
    public static final int TIME_OUT = 1005;
    public static final int PLAYER_NAME_IS_EMPTY = 1006;
    public static final int KEEP_TIME_IS_EMPTY = 1007;
    public static final int NO_USER = 1008;
    public static final int OLD_USER_ID_IS_EMPTY = 1009;
    public static final int NEW_USER_ID_IS_EMPTY = 1010;
    public static final int OLD_USER_ID_NOT_EXISTS = 1011;
    public static final int CUSTOMER_ID_IS_EMPTY = 1012;
    public static final int DATA_IS_EMPTY = 1013;
    public static final int IDENTIFY_IS_EMPTY = 1014;
    public static final int GATE_WAY_ID_IS_EMPTY = 1015;
    public static final int NO_ROLE = 1016;
    public static final int ORDER_ID_NOT_EXISTS = 1017;
    public static final int TICKET_IS_INVALID = 1018;
    public static final int TICKET_VERIFICATION_FAIL = 1019;
    public static final int USER_IP_IS_EMPTY = 1020;
    public static final int APPKEY_ID_IS_EMPTY = 1021;
    public static final int SESSION_ID_IS_EMPTY = 1022;
    public static final int CODE_IS_EMPTY = 1023;
    public static final String BAIDU_SYSTEMIN_ERROR = "ERROR_-1";
    public static final String BAIDU_PARAMETER_INVALID = "ERROR_-100";
    public static final String BAIDU_SYTEM_ERROR = "ERROR_-200";
    public static final String BAIDU_DATABASE_FIAL = "ERROR_-500";
    public static final String BAIDU_PLAYER_NOT_EXIST = "ERROR_1406";
    public static final String BAIDU_OVER_MAX_CALL = "ERROR_-1814";
    public static final String BAIDU_IP_INVALID = "ERROR_-11000";
    public static final int RENREN_LOGIN_FAIL = 1001;
    public static final int RENREN_QUERY_FAIL = 1002;
    public static final int RENREN_PAY_OK = 0;
    public static final int RENREN_PAY_PARAM_ERROR = -1;
    public static final int RENREN_PAY_NOT_ENOUGH = -2;
    public static final int RENREN_PAY_SYSTEM_ERROR = -3;
    public static final int RENREN_PAY_PERMISSION_DENY = -4;
    public static final int RENREN_PAY_ORDER_DUPLICATE = -5;
    public static final int KAIXIN001_LOGIN_FAIL = 1001;
    public static final String SOGOU_PAY_OK = "OK";
    public static final String SOGOU_PAY_INVALID_PARAM = "ERR_100";
    public static final String SOGOU_PAY_VALID_FAIL = "ERR_200";
    public static final String SOGOU_PAY_NO_USER = "ERR_300";
    public static final String SOGOU_PAY_INVALID_IP = "ERR_400";
    public static final String SOGOU_PAY_OTHER_ERROR = "ERR_500";
    public static final String FIVEONE_OK = "success";
    public static String FIVEONE_ERR_APPKEY;
    public static String FIVEONE_ERR_ORDERID;
    public static String FIVEONE_ERR_PRICE;
    public static String FIVEONE_ERR_GAMEBI;
    public static String FIVEONE_ERR_USER;
    public static String FIVEONE_ERR_AREAID;
    public static String FIVEONE_ERR_AREASIGN;
    public static final String SINA_NO_TICKET_NO_SESSION = "no_ticket_no_session";
    public static final String SINA_INVALID_TICKET = "invalid ticket";
    public static final String SINA_WRONG_PARAM = "wrong param";
    public static final String SINA_NOT_EXIST = "tickte not exist";
    public static final String SINA_TIMEOUT = "ticket time out";
    public static final String SINA_NOT_SUPPORT = "not supported";
    public static final String SINA_VRY_SUCC = "0";
    public static final String SINA_VRY_NOT_SUPPORT = "6204";
    public static final String SINA_VRY_TIMEOUT = "6203";
    public static final String SINA_VRY_NOT_EXIST = "6202";
    public static final String SINA_VRY_WRONG_PARAM = "6201";
    public static final int DUOWAN_LOGIN_FAIL = 1001;
    public static final int DUOWAN_LOGIN_TIMESTAMP_ERROR = 1002;
    public static final int DUOWAN_INSIDE_ERROR = -3;
    public static final int DUOWAN_PARAM_ERROR = -2;
    public static final int DUOWAN_CHECK_ERROR = -1;
    public static final int DUOWAN_PAY_SUCCESS = 1;
    public static final int DUOWAN_PAY_PARAM_ERROR = -10;
    public static final int DUOWAN_PAY_VERIFY_ERROR = -11;
    public static final int DUOWAN_PAY_TIMESTAMP_ERROR = -15;
    public static final int DUOWAN_PAY_ORDERID_DUPLICATE = -18;
    public static final int DUOWAN_PAY_ID_ERROR = -19;
    public static final int DUOWAN_PAY_FAIL = -20;
    public static final int DUOWAN_PAY_IP_ILLEGAL = -21;
    public static final int DUOWAN_PAY_UNKNOWN_ERROR = -100;
    public static final int DUOWAN_QUERY_USER_SUCCESS = 1;
    public static final int DUOWAN_QUERY_USER_UNKNOWN_ERROR = 0;
    public static final int DUOWAN_QUERY_USER_NOT_EXIST = 2;
    public static final int DUOWAN_QUERY_USER_IP_ERROR = 3;
    public static final int DUOWAN_QUERY_USER_PARAM_ERROR = 4;
    public static final int DUOWAN_QUERY_USER_NOT_EXIST_2 = -1;
    public static final int TAOBAO_COOP_ID_EMPTY = -1;
    public static final int TAOBAO_GAME_ID_EMPTY = -2;
    public static final int TAOBAO_GATEWAY_ID_EMPTY = -3;
    public static final int TAOBAO_UID_EMPTY = -4;
    public static final int TAOBAO_ISADULT_EMPTY = -5;
    public static final int TAOBAO_SIGN_EMPTY = -6;
    public static final int TAOBAO_CHARGEAMOUNT_EMPTY = -7;
    public static final int TAOBAO_CHARGEMONEY_EMPTY = -8;
    public static final int TAOBAO_ORDER_ID_EMPTY = -9;
    public static final int TAOBAO_USER_IP_EMPTY = -10;
    public static final int TAOBAO_PAYTIME_EMPTY = -11;
    public static final int TAOBAO_PAY_PARAM_ERROR = -12;
    public static final int TAOBAO_PAY_ID_ERROR = -13;
    public static final int TAOBAO_PAY_ORDERID_DUPLICATE = -14;
    public static final int TAOBAO_PAY_IP_ILLEGAL = -15;
    public static final int TAOBAO_YXOPERATION_EMPTY = -16;
    public static final int TAOBAO_NO_USERDTO = -17;
    public static final int TAOBAO_USER_NOT_ACTIVATED = -18;
    public static final int TAOBAO_LACK_PARAM = 101;
    public static final int TAOBAO_SIGN_FAIL = 102;
    public static final int TAOBAO_INSIDE_ERROR = 501;
    public static final int TAOBAO_RMB_GOLD_FACTOR = 10;
    public static final String TAOBAO_LOGIN_EXT_PARAM = "ext";
    public static final int TAOBAO_PAY_SUCCESS = 0;
    public static final int TAOBAO_QUERY_ACTIVATION_SUCCESS = 0;
    public static final int TAOBAO_PAY_FAIL = 502;
    public static final int TAOBAO_NOT_ACTIVATED = 0;
    public static final int TAOBAO_IS_ACTIVATED = 1;
    public static final int XUNLEI_PAY_SUCCESS = 1;
    public static final int XUNLEI_PAY_ORDER_DUPLICATION = 2;
    public static final int XUNLEI_PAY_PARAMS_NOT_COMPLETE = -1;
    public static final int XUNLEI_PAY_CHECK_FAILED = -2;
    public static final int XUNLEI_PAY_USER_NOT_EXIST = -3;
    public static final int XUNLEI_PAY_REQUEST_TIMEOUT = -4;
    public static final int XUNLEI_PAY_INVALID_SERVERID = -5;
    public static final int XUNLEI_PAY_IP_FORBIDDEN = -6;
    public static final int XUNLEI_PAY_UNSUPPORTED_URL_DECODE = -7;
    public static final int XUNLEI_PAY_WRONG_USER = -8;
    public static final int XUNLEI_PAY_OTHER_ERRORS = -9;
    public static final int XUNLEI_PAY_EXCEPTION = -10;
    public static final int XUNLEI_QUERY_PLAYER_SUCCESS = 0;
    public static final int XUNLEI_QUERY_PLAYER_PARAMS_NOT_COMPLETE = -1;
    public static final int XUNLEI_QUERY_PLAYER_CHECK_FAILED = -2;
    public static final int XUNLEI_QUERY_PLAYER_NOT_EXIST = -3;
    public static final int XUNLEI_QUERY_ONLINE_TIME_SUCCESS = 0;
    public static final int XUNLEI_QUERY_ONLINE_TIME_PLAYER_PARAMS_NOT_COMPLETE = -1;
    public static final int XUNLEI_QUERY_ONLINE_TIME_PLAYER_CHECK_FAILED = -2;
    public static final int XUNLEI_ONLINE_TIME_QUERY_PLAYER_NOT_EXIST = -3;
    public static final int XUNLEI_USERINFO_IS_EMPTY = 1004;
    public static final int XUNLEI_SERVERID_IS_EMPTY = 1005;
    public static final int XUNLEI_SERVERFLAG_IS_EMPTY = 1006;
    public static final int XUNLEI_WRONG_BASE64 = 1007;
    public static final int XUNLEI_AUTH_RESULT_IS_NULL = 1007;
    public static final int XUNLEI_AUTH_NUMBER_EXCEPTION = 1008;
    public static final int XUNLEI_AUTH_EXCEPTION = 1009;
    public static final int XUNLEI_TIMESTAMP_EXPIRED = 1010;
    public static final int XUNLEI_URLDECODE_EXCEPTION = 1011;
    public static final int YX_360_PARAM_ERROR = -1;
    public static final int YX_360_TIME_OUT = -2;
    public static final int YX_360_PARAM_CHECK_FAIL = -3;
    public static final int YX_360_PARAM_MISSING_PARAM = -4;
    public static final int YX_360_SERVER_IP_IS_FORBIDDEN = -5;
    public static final int YX_360_REQUEST_NUM_TOO_MAX = -6;
    public static final int YX_360_CAN_NOT_QUERY_DATA = -7;
    public static final int YX_360_SERVER_EXCEPTION = -103;
    public static final int YX_JD_IP_IS_FORBIDDEN = 104;
    public static final String YX_JD_IP_IS_FORBIDDEN_MESSAGE = "IP\u5730\u5740\u4e0d\u7b26\u5408\u8981\u6c42";
    public static final int YX_JD_PARAM_ERROR = 103;
    public static final String YX_JD_PARAM_ERROR_MESSAGE = "\u4f20\u5165\u7684\u53c2\u6570\u6709\u8bef";
    public static final int YX_JD_GATE_WAY_ID_IS_EMPTY = 107;
    public static final String YX_JD_GATE_WAY_ID_IS_EMPTY_MESSAGE = "\u533a\u670did\u4e0d\u5b58\u5728\u6216\u8005\u9519\u8bef";
    public static final int YX_JD_TICKET_ERROR = 105;
    public static final String YX_JD_TICKET_ERROR_MESSAGE = "\u9a8c\u8bc1\u6458\u8981\u4e32\u9a8c\u8bc1\u5931\u8d25";
    public static final int YX_JD_SUCCESS = 100;
    public static final String YX_JD_SUCCESS_MESSAGE = "\u6210\u529f";
    public static final int YX_JD_ORDER_ID_IS_EXSITED = 102;
    public static final String YX_JD_ORDER_ID_IS_EXSITED_MESSAGE = "\u8ba2\u5355\u53f7\u4e0d\u5141\u8bb8\u91cd\u590d";
    public static final int YX_JD_SYSTEM_ERROR = 999;
    public static final String YX_JD_YX_JD_SYSTEM_ERROR_MESSAGE = "\u7cfb\u7edf\u9519\u8bef";
    public static final int YX_JD_NO_ROLE = 108;
    public static final String YX_JD_NO_ROLE_MESSAGE = "\u89d2\u8272\u4e0d\u5b58\u5728(\u8be5\u7528\u6237\u6ca1\u6709\u521b\u5efa\u89d2\u8272)";
    public static final int YX_JD_ORDER_ID_NOT_EXISTS = 101;
    public static final String YX_JD_ORDER_ID_NOT_EXISTS_MESSAGE = "\u8ba2\u5355\u4e0d\u5b58\u5728";
    public static final int YX_SINA_SUCCESS = 0;
    public static final int YX_SINA_SPID_IS_EMPTY = 200;
    public static final int YX_SINA_SPID_IS_EMPTY_1 = 100;
    public static final int YX_SINA_SPID_IS_EMPTY_3 = 300;
    public static final String YX_SINA_SPID_IS_EMPTY_MESSAGE = "SPID\u4fe1\u606f\u4e0d\u5b8c\u6574\u6216\u4fe1\u606f\u6709\u8bef";
    public static final int YX_SINA_SERVERID_IS_EMPTY = 201;
    public static final int YX_SINA_SERVERID_IS_EMPTY_1 = 101;
    public static final int YX_SINA_SERVERID_IS_EMPTY_3 = 301;
    public static final String YX_SINA_SERVERID_IS_EMPTY_MESSAGE = "ServerId\u4fe1\u606f\u4e0d\u5b8c\u6574\u6216\u4fe1\u606f\u6709\u8bef";
    public static final int YX_SINA_USER_ID_IS_EMPTY = 202;
    public static final int YX_SINA_USER_ID_IS_EMPTY_1 = 102;
    public static final int YX_SINA_USER_ID_IS_EMPTY_3 = 302;
    public static final String YX_SINA_USER_ID_IS_EMPTY_MESSAGE = "UserId\u4fe1\u606f\u4e0d\u5b8c\u6574\u6216\u4fe1\u606f\u6709\u8bef";
    public static final int YX_SINA_ROLEID_IS_EMPTY = 203;
    public static final int YX_SINA_ROLEID_IS_EMPTY_3 = 303;
    public static final String YX_SINA_ROLEID_IS_EMPTY_MESSAGE = "RoleId\u4fe1\u606f\u4e0d\u5b8c\u6574\u6216\u4fe1\u606f\u6709\u8bef";
    public static final int YX_SINA_ORDERID_IS_EMPTY = 204;
    public static final int YX_SINA_ORDERID_IS_EMPTY_3 = 302;
    public static final String YX_SINA_ORDERID_IS_EMPTY_MESSAGE = "OrderId\u4fe1\u606f\u4e0d\u5b8c\u6574\u6216\u4fe1\u606f\u6709\u8bef";
    public static final int YX_SINA_GAMEPOINT_IS_EMPTY = 205;
    public static final int YX_SINA_GAMEPOINT_IS_EMPTY_3 = 305;
    public static final String YX_SINA_GAMEPOINT_IS_EMPTY_MESSAGE = "GamePoint\u4fe1\u606f\u4e0d\u5b8c\u6574\u6216\u4fe1\u606f\u6709\u8bef";
    public static final int YX_SINA_SIGN_IS_EMPTY = 206;
    public static final int YX_SINA_SIGN_IS_EMPTY_1 = 103;
    public static final int YX_SINA_SIGN_IS_EMPTY_3 = 306;
    public static final String YX_SINA_SIGN_IS_EMPTY_MESSAGE = "Sign\u4fe1\u606f\u4e0d\u5b8c\u6574\u6216\u4fe1\u606f\u6709\u8bef";
    public static final int YX_SINA_SIGN_ERROR = 210;
    public static final int YX_SINA_SIGN_ERROR_1 = 110;
    public static final int YX_SINA_SIGN_ERROR_3 = 310;
    public static final String YX_SINA_SIGN_ERROR_MESSAGE = "\u7b7e\u540d\u9519\u8bef";
    public static final int YX_SINA_IP_IS_FORBIDDEN = 211;
    public static final int YX_SINA_IP_IS_FORBIDDEN_1 = 111;
    public static final int YX_SINA_IP_IS_FORBIDDEN_3 = 311;
    public static final String YX_SINA_IP_IS_FORBIDDEN_MESSAGE = "IP\u4e0d\u5728\u5141\u8bb8\u7684\u5217\u8868\u91cc\u9762";
    public static final int YX_SINA_USER_ID_NOT_EXISTS = 212;
    public static final int YX_SINA_USER_ID_NOT_EXISTS_1 = 112;
    public static final int YX_SINA_USER_ID_NOT_EXISTS_3 = 312;
    public static final String YX_SINA_USER_ID_NOT_EXISTS_MESSAGE = "\u6e38\u620f\u8d26\u6237\u4e0d\u5b58\u5728";
    public static final int YX_SINA_PLAYER_ID_NOT_EXISTS = 213;
    public static final int YX_SINA_PLAYER_ID_NOT_EXISTS_1 = 121;
    public static final String YX_SINA_PLAYER_ID_NOT_EXISTS_MESSAGE = "\u6e38\u620f\u89d2\u8272\u672a\u521b\u5efa\u6216\u8005\u6e38\u620f\u89d2\u8272\u4e0d\u5b58\u5728";
    public static final int YX_SINA_PAY_FAIL = 215;
    public static final String YX_SINA_PAY_FAIL_MESSAGE = "\u7ed9\u7528\u6237\u8d26\u6237\u5145\u503c\u5931\u8d25";
    public static final int YX_SINA_ORDER_ID_EXISTS = 216;
    public static final String YX_SINA_ORDER_ID_EXISTS_MESSAGE = "\u8ba2\u5355\u53f7\u91cd\u590d\u5145\u503c\u5931\u8d25";
    public static final int YX_SINA_PAY_POINT_IS_EMPTY = 220;
    public static final String YX_SINA_PAY_POINT_IS_EMPTY_MESSAGE = "PayPoint\u4fe1\u606f\u4e0d\u5b8c\u6574\u6216\u4fe1\u606f\u6709\u8bef";
    public static final int YX_SINA_ORDER_ID_NOT_EXISTS = 320;
    public static final int YX_SINA_START_TIME_IS_EMPTY = 324;
    public static final String YX_SINA_START_TIME_IS_EMPTY_MESSAGE = "\u6279\u91cf\u67e5\u8be2\u8d77\u59cb\u65f6\u95f4\u4e0d\u80fd\u4e3a\u7a7a";
    public static final int YX_SINA_END_TIME_IS_EMPTY = 325;
    public static final String YX_SINA_END_TIME_IS_EMPTY_MESSAGE = "\u6279\u91cf\u67e5\u8be2\u7ed3\u675f\u65f6\u95f4\u4e0d\u80fd\u4e3a\u7a7a";
    public static final String YX_TAOBAO_ERROR_CODE_0101 = "0101";
    public static final String YX_TAOBAO_ERROR_CODE_0102 = "0102";
    public static final String YX_TAOBAO_ERROR_CODE_0104 = "0104";
    public static final String YX_TAOBAO_ERROR_CODE_0108 = "0101";
    public static final String YX_TAOBAO_ERROR_CODE_0109 = "0101";
    public static final String YX_TAOBAO_ERROR_CODE_0110 = "0101";
    public static final String YX_TAOBAO_ERROR_CODE_0301 = "0301";
    public static final String YX_TAOBAO_ERROR_CODE_0305 = "0305";
    public static final String YX_TAOBAO_ERROR_CODE_0306 = "0306";
    public static final int YX_TENCENT_PARAMS_EMPTY = 1100;
    public static final String YX_TENCENT_PARAMS_EMPTY_MSG = "\u53c2\u6570\u4e0d\u80fd\u4e3a\u7a7a";
    public static final int YX_TENCENT_REGEX_CHECK_FAILED = 1101;
    public static final int YX_TENCENT_INVALID_PLATFORM = 1102;
    public static final String YX_TENCENT_INVALID_PLATFORM_MSG = "\u975e\u6cd5\u7684\u5e73\u53f0\u6765\u6e90";
    public static final int YX_TENCENT_PAY_SUCCESS = 0;
    public static final String YX_TENCENT_PAY_SUCCESS_MSG = "OK";
    public static final int YX_TENCENT_PAY_BUSY = 1;
    public static final String YX_TENCENT_PAY_BUSY_MSG = "\u7cfb\u7edf\u7e41\u5fd9";
    public static final int YX_TENCENT_PAY_TOKEN_EXPIRED = 2;
    public static final String YX_TENCENT_PAY_TOKEN_EXPIRED_MSG = "TOKEN\u5df2\u8fc7\u671f";
    public static final int YX_TENCENT_PAY_TOKEN_NOT_EXISTS = 3;
    public static final String YX_TENCENT_PAY_TOKEN_NOT_EXISTS_MSG = "TOKEN\u4e0d\u5b58\u5728";
    public static final int YX_TENCENT_PAY_INVALID_PARAMS = 4;
    public static final String YX_TENCENT_PAY_INVALID_PARAMS_MSG = "\u8bf7\u6c42\u53c2\u6570\u9519\u8bef\uff1a";
    public static final int YX_TENCENT_PAY_ORDER_EXISTS = 5;
    public static final String YX_TENCENT_PAY_ORDER_EXISTS_MSG = "\u8ba2\u5355\u53f7\u91cd\u590d";
    public static final int YX_TENCENT_PAY_NO_SUCH_ROLE = 6;
    public static final String YX_TENCENT_PAY_NO_SUCH_ROLE_MSG = "\u89d2\u8272\u4e0d\u5b58\u5728";
    public static final int YX_TENCENT_PAY_INVALID_USER = 7;
    public static final String YX_TENCENT_PAY_INVALID_USER_MSG = "\u975e\u6cd5\u7528\u6237";
    public static final int YX_TENCENT_PAY_EXCEPTION = 8;
    public static final String YX_TENCENT_PAY_EXCEPTION_MSG = "\u5145\u503c\u5f02\u5e38";
    public static final int YX_TENCENT_PAY_UNKNOWN_ERROR = 9;
    public static final String YX_TENCENT_PAY_UNKNOWN_ERROR_MSG = "\u672a\u77e5\u9519\u8bef";
    public static final int YX_TENCENT_PAY_TICKET_CHECK_FAILED_TX = 12;
    public static final String YX_TENCENT_PAY_TICKET_CHECK_FAILED_TX_MSG = "\u817e\u8baf\u7b7e\u540d\u9a8c\u8bc1\u5931\u8d25";
    public static final int YX_TENCENT_PAY_TICKET_CHECK_FAILED_KINGNET = 13;
    public static final String YX_TENCENT_PAY_TICKET_CHECK_FAILED_KINGNET_MSG = "\u607a\u82f1\u7b7e\u540d\u9a8c\u8bc1\u5931\u8d25";
    public static final int YX_TENCENT_LOGIN_EXCEPTION = 14;
    public static final String YX_TENCENT_LOGIN_EXCEPTION_MSG = "\u767b\u5f55\u5f02\u5e38";
    public static final int YX_TENCENT_CONFIRM_DELIVERY_SUCCESS = 10;
    public static final String YX_TENCENT_CONFIRM_DELIVERY_SUCCESS_MSG = "confirm delivery ok!";
    public static final int YX_TENCENT_CONFIRM_DELIVERY_EXCEPTION = 11;
    public static final String YX_TENCENT_CONFIRM_DELIVERY_EXCEPTION_MSG = "confirm delivery EXCEPTION!";
    public static final int YX_10086_SUCCESS = 200;
    public static final String YX_10086_SUCCESS_MSG = "\u6210\u529f";
    public static final int YX_10086_TICKET_IS_ERROR = 201;
    public static final String YX_10086_TICKET_IS_ERROR_MSG = "Md5\u52a0\u5bc6\u53c2\u6570\u9519\u8bef";
    public static final int YX_10086_USER_ID_NOT_EXISTS = 202;
    public static final String YX_10086_USER_ID_NOT_EXISTS_MSG = "\u8d26\u53f7\u4e0d\u5b58\u5728";
    public static final int YX_10086_ORDER_ID_EXISTS = 203;
    public static final String YX_10086_ORDER_ID_EXISTS_MSG = "\u8ba2\u5355\u5df2\u5904\u7406";
    public static final int YX_10086_SERVER_ID_IS_EMPTY = 204;
    public static final String YX_10086_SERVER_ID_IS_EMPTY_MSG = "\u6e38\u620f\u533a\u7f16\u53f7\u9519\u8bef";
    public static final int YX_10086_MONEY_IS_EMPTY = 207;
    public static final String YX_10086_MONEY_IS_EMPTY_MSG = "\u5145\u503c\u91d1\u989d\u6709\u8bef";
    public static final int YX_10086_ORDER_ID_IS_EMPTY = 206;
    public static final String YX_10086_ORDER_ID_IS_EMPTY_MSG = "\u8ba2\u5355\u4e0d\u5b58\u5728";
    public static final int YX_10086_IP_IS_FORBIDDEN = 207;
    public static final String YX_10086_IP_IS_FORBIDDEN_MSG = "IP\u9274\u6743\u5931\u8d25";
    public static final int YX_10086_PAY_FAIL = 208;
    public static final String YX_10086_PAY_FAIL_MSG = "\u8ba2\u5355\u5904\u7406\u5931\u8d25";
    public static final int YX_10086_FAIL = -1;
    public static final String YX_10086_FAIL_MSG = "\u5931\u8d25";
    public static final int CODE_RESPONSE_IS_EMPTY = 1;
    public static final int ACCESS_RESPONSE_IS_EMPTY = 2;
    public static final String TICKET_VERIFICATION_FAIL_MSG = "\u6821\u9a8c\u5931\u8d25";
    public static final String PARAM_ERROR_MSG = "\u53c2\u6570\u9519\u8bef";
    
    static {
        YxOperationErrors.FIVEONE_ERR_APPKEY = "1";
        YxOperationErrors.FIVEONE_ERR_ORDERID = "2";
        YxOperationErrors.FIVEONE_ERR_PRICE = "3";
        YxOperationErrors.FIVEONE_ERR_GAMEBI = "4";
        YxOperationErrors.FIVEONE_ERR_USER = "5";
        YxOperationErrors.FIVEONE_ERR_AREAID = "6";
        YxOperationErrors.FIVEONE_ERR_AREASIGN = "7";
    }
    
    public static String translateToBaiduErrorCode(final int errorCode) {
        if (901 == errorCode || 911 == errorCode || 912 == errorCode) {
            return "ERROR_-200";
        }
        if (902 == errorCode || 903 == errorCode || 904 == errorCode || 907 == errorCode || 909 == errorCode || 910 == errorCode) {
            return "ERROR_-100";
        }
        if (905 == errorCode || 906 == errorCode || 913 == errorCode || 914 == errorCode || 915 == errorCode) {
            return "ERROR_-1";
        }
        if (916 == errorCode) {
            return "ERROR_1406";
        }
        return null;
    }
    
    public static String translateToSogouErrorCode(final int errorCode) {
        if (1 == errorCode || 917 == errorCode) {
            return "OK";
        }
        if (908 == errorCode) {
            return "ERR_400";
        }
        if (909 == errorCode || 918 == errorCode) {
            return "ERR_500";
        }
        if (902 == errorCode || 903 == errorCode || 904 == errorCode || 907 == errorCode || 909 == errorCode || 910 == errorCode) {
            return "ERR_100";
        }
        if (916 == errorCode) {
            return "ERR_300";
        }
        return "ERR_500";
    }
    
    public static String translateToFiveoneErrorCode(final int errorCode) {
        return new StringBuilder().append(errorCode).toString();
    }
}
