package com.reign.kf.comm.protocol;

import java.util.concurrent.atomic.*;

public class Command
{
    private static final AtomicInteger id;
    public static final int QUERY_SEASONINFO;
    public static final int UPDATE_SEASONINFO;
    public static final int QUERY_MATCHSTATE;
    public static final int SIGN;
    public static final int QUERY_MATCHSCHEDULE;
    public static final int QUERY_MATCHRTINFO;
    public static final int QUERY_MATCHREPORT;
    public static final int QUERY_TURNRANK;
    public static final int QUERY_MATCHNUMSCHEDULE;
    public static final int QUERY_MATCHRESULT;
    public static final int SYNC;
    public static final int QUERY_AUCTIONINFO;
    public static final int UPDATE_AUCTIONINFO;
    public static final int SIGN_AUCTIONPLAYER;
    public static final int PUT_GENERAL;
    public static final int TAKEOFF_GENERAL;
    public static final int BID;
    public static final int AUCTION_SYNC;
    public static final int QUERY_RIVALINFO;
    public static final int UPDATE_RIVALINFO;
    public static final int RSIGN;
    public static final int RCANELSIGN;
    public static final int RSYNC;
    public static final int RQUERY_MATCHSCHEDULE;
    public static final int RQUERY_RTINFO;
    public static final int RQUERY_MATCHRESULT;
    public static final int UPDATE_RIVALSEASON;
    public static final int RQUERY_NEXTMATCH;
    public static final int PUT_GENERAL_NEW;
    public static final int AUCTION_SYNC_NEW;
    public static final int GZ_REGISTER;
    public static final int GZ_QUERYMATCH;
    public static final int GZ_UPDATEMATCH;
    public static final int GZ_UPDATEMATCHRESTARTFLAG;
    public static final int GZ_UPDATEMATCHFINISH;
    public static final int GZ_GAME_SERVER_LOGIN;
    public static final int GZ_GAME_SERVER_GET_MATCH_STATE;
    public static final int GZ_GAME_SERVER_SIGN_UP;
    public static final int GZ_QUERY;
    public static final int GZ_ALIVE;
    public static final int INSPIRE;
    public static final int KFWD_GW_SEASONINFO;
    public static final int KFWD_GW_SCHEDULEINFO;
    public static final int KFWD_GW_REWARDINFO;
    public static final int KFWD_GW_TICKETMARKETINFO;
    public static final int KFWD_GW_SEASONINFO_FROM_MATCH;
    public static final int KFWD_GW_SCHEDULEINFO_FROM_MATCH;
    public static final int KFWD_GW_REWARDINFO_FROM_MATCH;
    public static final int KFWD_SIGN_FROM_GAMESERVER;
    public static final int KFWD_SYNDATA_FROM_GAMESERVER;
    public static final int KFWD_RT_MATCH;
    public static final int KFWD_RT_MATCH_DISPLAY;
    public static final int KFWD_RT_RANKING_LIST;
    public static final int KFWD_STATE;
    public static final int KFWD_DOUBLEREWARD;
    public static final int KFWD_REWARDTICKETINFO;
    public static final int KFWD_GAMESERVERREWARDTICKETINFO;
    public static final int KFWD_GAMESERVERDAYBATTLEENDNOTICE;
    public static final int KFGZ_SIGN_FROM_GAMESERVER;
    public static final int KFGZ_SYNDATA_FROM_GAMESERVER;
    public static final int KFGZ_GW_GETSEASONINFO_FROM_GAME_SERVER;
    public static final int KFGZ_GW_GETSCHEDULEINFO_FROM_GAME_SERVER;
    public static final int KF_GETCID_FROM_GAME_SEVERR;
    public static final int KFGZ_GW_GETRULEINFO;
    public static final int KFGZ_GW_GETREWARDINFO;
    public static final int KFGZ_GW_GETSEASONINFO_FROM_MATCH;
    public static final int KFGZ_GW_GETSCHEDULEINFO_FROM_MATCH;
    public static final int KFGZ_GET_MATCH_GZINFO_FROM_GAMESERVER;
    public static final int KFGZ_GET_MATCH_GZRESULT_FROM_GAMESERVER;
    public static final int KFGZ_GW_GETAllSCHEDULEINFO_FROM_GAME_SERVER;
    public static final int KFGZ_GW_PUSHBATTLERESULT_FROM_MATCH;
    public static final int KFGZ_GW_GETBATTLERRANKING_FROM_GAME_SERVER;
    public static final int KFZB_GW_SEASONINFO;
    public static final int KFZB_GW_REWARDINFO;
    public static final int KFZB_GW_SEASONINFO_FROM_MATCH;
    public static final int KFZB_GW_REWARDINFO_FROM_MATCH;
    public static final int KFZB_GW_PLAYERLIMIT;
    public static final int KFZB_SIGN_FROM_GAMESERVER;
    public static final int KFZB_SYNDATA_FROM_GAMESERVER;
    public static final int KFZB_STATE;
    public static final int KFZB_GET_PHASE1_REWARD_INFO;
    public static final int KFZB_GET_PHASE2_MATCH_DETAIL_INFO;
    public static final int KFZB_RT_SUPPORT;
    public static final int KFZB_PLAYER_GID;
    public static final int KFZB_WINNER_INFO;
    public static final int KFZB_GETTOP16PLAYERINFO;
    public static final int SI_SYNFEAST_INFO;
    public static final int SI_PATICIPATEFEAST;
    public static final int SI_ORGANIZER_ADDFEAST;
    public static final int SI_FEASTROOMINFO;
    public static final int KFWD_GW_TREASURE_REWARDINFO;
    
    static {
        id = new AtomicInteger(1);
        QUERY_SEASONINFO = Command.id.getAndIncrement();
        UPDATE_SEASONINFO = Command.id.getAndIncrement();
        QUERY_MATCHSTATE = Command.id.getAndIncrement();
        SIGN = Command.id.getAndIncrement();
        QUERY_MATCHSCHEDULE = Command.id.getAndIncrement();
        QUERY_MATCHRTINFO = Command.id.getAndIncrement();
        QUERY_MATCHREPORT = Command.id.getAndIncrement();
        QUERY_TURNRANK = Command.id.getAndIncrement();
        QUERY_MATCHNUMSCHEDULE = Command.id.getAndIncrement();
        QUERY_MATCHRESULT = Command.id.getAndIncrement();
        SYNC = Command.id.getAndIncrement();
        QUERY_AUCTIONINFO = Command.id.getAndIncrement();
        UPDATE_AUCTIONINFO = Command.id.getAndIncrement();
        SIGN_AUCTIONPLAYER = Command.id.getAndIncrement();
        PUT_GENERAL = Command.id.getAndIncrement();
        TAKEOFF_GENERAL = Command.id.getAndIncrement();
        BID = Command.id.getAndIncrement();
        AUCTION_SYNC = Command.id.getAndIncrement();
        QUERY_RIVALINFO = Command.id.getAndIncrement();
        UPDATE_RIVALINFO = Command.id.getAndIncrement();
        RSIGN = Command.id.getAndIncrement();
        RCANELSIGN = Command.id.getAndIncrement();
        RSYNC = Command.id.getAndIncrement();
        RQUERY_MATCHSCHEDULE = Command.id.getAndIncrement();
        RQUERY_RTINFO = Command.id.getAndIncrement();
        RQUERY_MATCHRESULT = Command.id.getAndIncrement();
        UPDATE_RIVALSEASON = Command.id.getAndIncrement();
        RQUERY_NEXTMATCH = Command.id.getAndIncrement();
        PUT_GENERAL_NEW = Command.id.getAndIncrement();
        AUCTION_SYNC_NEW = Command.id.getAndIncrement();
        GZ_REGISTER = Command.id.getAndIncrement();
        GZ_QUERYMATCH = Command.id.getAndIncrement();
        GZ_UPDATEMATCH = Command.id.getAndIncrement();
        GZ_UPDATEMATCHRESTARTFLAG = Command.id.getAndIncrement();
        GZ_UPDATEMATCHFINISH = Command.id.getAndIncrement();
        GZ_GAME_SERVER_LOGIN = Command.id.getAndIncrement();
        GZ_GAME_SERVER_GET_MATCH_STATE = Command.id.getAndIncrement();
        GZ_GAME_SERVER_SIGN_UP = Command.id.getAndIncrement();
        GZ_QUERY = Command.id.getAndIncrement();
        GZ_ALIVE = Command.id.getAndIncrement();
        INSPIRE = Command.id.getAndIncrement();
        KFWD_GW_SEASONINFO = Command.id.getAndIncrement();
        KFWD_GW_SCHEDULEINFO = Command.id.getAndIncrement();
        KFWD_GW_REWARDINFO = Command.id.getAndIncrement();
        KFWD_GW_TICKETMARKETINFO = Command.id.getAndIncrement();
        KFWD_GW_SEASONINFO_FROM_MATCH = Command.id.getAndIncrement();
        KFWD_GW_SCHEDULEINFO_FROM_MATCH = Command.id.getAndIncrement();
        KFWD_GW_REWARDINFO_FROM_MATCH = Command.id.getAndIncrement();
        KFWD_SIGN_FROM_GAMESERVER = Command.id.getAndIncrement();
        KFWD_SYNDATA_FROM_GAMESERVER = Command.id.getAndIncrement();
        KFWD_RT_MATCH = Command.id.getAndIncrement();
        KFWD_RT_MATCH_DISPLAY = Command.id.getAndIncrement();
        KFWD_RT_RANKING_LIST = Command.id.getAndIncrement();
        KFWD_STATE = Command.id.getAndIncrement();
        KFWD_DOUBLEREWARD = Command.id.getAndIncrement();
        KFWD_REWARDTICKETINFO = Command.id.getAndIncrement();
        KFWD_GAMESERVERREWARDTICKETINFO = Command.id.getAndIncrement();
        KFWD_GAMESERVERDAYBATTLEENDNOTICE = Command.id.getAndIncrement();
        KFGZ_SIGN_FROM_GAMESERVER = Command.id.getAndIncrement();
        KFGZ_SYNDATA_FROM_GAMESERVER = Command.id.getAndIncrement();
        KFGZ_GW_GETSEASONINFO_FROM_GAME_SERVER = Command.id.getAndIncrement();
        KFGZ_GW_GETSCHEDULEINFO_FROM_GAME_SERVER = Command.id.getAndIncrement();
        KF_GETCID_FROM_GAME_SEVERR = Command.id.getAndIncrement();
        KFGZ_GW_GETRULEINFO = Command.id.getAndIncrement();
        KFGZ_GW_GETREWARDINFO = Command.id.getAndIncrement();
        KFGZ_GW_GETSEASONINFO_FROM_MATCH = Command.id.getAndIncrement();
        KFGZ_GW_GETSCHEDULEINFO_FROM_MATCH = Command.id.getAndIncrement();
        KFGZ_GET_MATCH_GZINFO_FROM_GAMESERVER = Command.id.getAndIncrement();
        KFGZ_GET_MATCH_GZRESULT_FROM_GAMESERVER = Command.id.getAndIncrement();
        KFGZ_GW_GETAllSCHEDULEINFO_FROM_GAME_SERVER = Command.id.getAndIncrement();
        KFGZ_GW_PUSHBATTLERESULT_FROM_MATCH = Command.id.getAndIncrement();
        KFGZ_GW_GETBATTLERRANKING_FROM_GAME_SERVER = Command.id.getAndIncrement();
        KFZB_GW_SEASONINFO = Command.id.getAndIncrement();
        KFZB_GW_REWARDINFO = Command.id.getAndIncrement();
        KFZB_GW_SEASONINFO_FROM_MATCH = Command.id.getAndIncrement();
        KFZB_GW_REWARDINFO_FROM_MATCH = Command.id.getAndIncrement();
        KFZB_GW_PLAYERLIMIT = Command.id.getAndIncrement();
        KFZB_SIGN_FROM_GAMESERVER = Command.id.getAndIncrement();
        KFZB_SYNDATA_FROM_GAMESERVER = Command.id.getAndIncrement();
        KFZB_STATE = Command.id.getAndIncrement();
        KFZB_GET_PHASE1_REWARD_INFO = Command.id.getAndIncrement();
        KFZB_GET_PHASE2_MATCH_DETAIL_INFO = Command.id.getAndIncrement();
        KFZB_RT_SUPPORT = Command.id.getAndIncrement();
        KFZB_PLAYER_GID = Command.id.getAndIncrement();
        KFZB_WINNER_INFO = Command.id.getAndIncrement();
        KFZB_GETTOP16PLAYERINFO = Command.id.getAndIncrement();
        SI_SYNFEAST_INFO = Command.id.getAndIncrement();
        SI_PATICIPATEFEAST = Command.id.getAndIncrement();
        SI_ORGANIZER_ADDFEAST = Command.id.getAndIncrement();
        SI_FEASTROOMINFO = Command.id.getAndIncrement();
        KFWD_GW_TREASURE_REWARDINFO = Command.id.getAndIncrement();
    }
}
